In [153]:
 pip install selenium==4.20.0

Requirement already satisfied: selenium==4.20.0 in c:\users\steph\anaconda3\lib\site-packages (4.20.0)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\steph\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium==4.20.0) (2.2.3)
Requirement already satisfied: trio~=0.17 in c:\users\steph\anaconda3\lib\site-packages (from selenium==4.20.0) (0.28.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\steph\anaconda3\lib\site-packages (from selenium==4.20.0) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\steph\anaconda3\lib\site-packages (from selenium==4.20.0) (2024.8.30)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\steph\anaconda3\lib\site-packages (from selenium==4.20.0) (4.11.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\steph\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.20.0) (24.3.0)
Requirement already satisfied: sortedcontainers in c:\users\steph\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.20.0) (2.4.0)
Requirement already satisfied: idna in c:\users\steph\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.20.0) (3.7)
Requirement already satisfied: outcome in c:\users\steph\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.20.0) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\steph\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.20.0) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\steph\anaconda3\lib\site-packages (from trio~=0.17->selenium==4.20.0) (1.17.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\steph\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium==4.20.0) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\steph\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium==4.20.0) (1.7.1)
Requirement already satisfied: pycparser in c:\users\steph\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium==4.20.0) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\steph\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.20.0) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

In [154]:
pip install webdriver-manager==4.0.1

^C
Note: you may need to restart the kernel to use updated packages.

In [1]:
import json,requests
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import time
from unidecode import unidecode
import numpy as np

from webdriver_manager.chrome import ChromeDriverManager

In [156]:
import requests
from bs4 import BeautifulSoup
from datetime import datetime

### OPENING CHROME WITH SELENIUM

In [3]:
service = ChromeService(r"C:\Users\steph\.wdm\drivers\chromedriver-win64 (1)\chromedriver-win64\chromedriver.exe")
options = Options()
driver = webdriver.Chrome(service=service, options=options)

options = webdriver.ChromeOptions()
options.set_capability(
    "goog:loggingPrefs", {"performance": "ALL", "browser": "ALL"}
)
#driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=options)
driver.set_page_load_timeout(50)

#driver.get("https://sofifa.com/players?type=all&ct%5B0%5D=8&na%5B0%5D=97&na%5B1%5D=101&na%5B2%5D=104&na%5B3%5D=103&na%5B4%5D=110&na%5B5%5D=108&na%5B6%5D=111&na%5B7%5D=117&na%5B8%5D=118&na%5B9%5D=126&na%5B10%5D=129&na%5B11%5D=133&na%5B12%5D=136&na%5B13%5D=140&na%5B14%5D=145&lg%5B0%5D=13&lg%5B1%5D=31&lg%5B2%5D=53&lg%5B3%5D=19&lg%5B4%5D=16&showCol%5B0%5D=ae&showCol%5B1%5D=hi&showCol%5B2%5D=wi&showCol%5B3%5D=pf&showCol%5B4%5D=pt&showCol%5B5%5D=gu&showCol%5B6%5D=vl&showCol%5B7%5D=wg&showCol%5B8%5D=cr&showCol%5B9%5D=fi&showCol%5B10%5D=he&showCol%5B11%5D=sh&showCol%5B12%5D=vo&showCol%5B13%5D=dr&showCol%5B14%5D=cu&showCol%5B15%5D=fr&showCol%5B16%5D=lo&showCol%5B17%5D=bl&showCol%5B18%5D=ac&showCol%5B19%5D=sp&showCol%5B20%5D=ag&showCol%5B21%5D=re&showCol%5B22%5D=ba&showCol%5B23%5D=so&showCol%5B24%5D=ju&showCol%5B25%5D=st&showCol%5B26%5D=sr&showCol%5B27%5D=ln&showCol%5B28%5D=ar&showCol%5B29%5D=in&showCol%5B30%5D=vi&showCol%5B31%5D=pe&showCol%5B32%5D=cm&showCol%5B33%5D=ma&showCol%5B34%5D=sa&showCol%5B35%5D=sl&showCol%5B36%5D=gd&showCol%5B37%5D=gh&showCol%5B38%5D=gc&showCol%5B39%5D=gp&showCol%5B40%5D=gr&showCol%5B41%5D=wk&showCol%5B42%5D=sk&r=220002&set=true")
#driver.get("https://sofifa.com/players?type=all&ct%5B0%5D=8&na%5B0%5D=97&na%5B1%5D=101&na%5B2%5D=104&na%5B3%5D=103&na%5B4%5D=110&na%5B5%5D=108&na%5B6%5D=111&na%5B7%5D=117&na%5B8%5D=118&na%5B9%5D=126&na%5B10%5D=129&na%5B11%5D=133&na%5B12%5D=136&na%5B13%5D=140&na%5B14%5D=145&lg%5B0%5D=13&lg%5B1%5D=31&lg%5B2%5D=53&lg%5B3%5D=19&lg%5B4%5D=16&showCol%5B0%5D=ae&showCol%5B1%5D=hi&showCol%5B2%5D=wi&showCol%5B3%5D=pf&showCol%5B4%5D=pt&showCol%5B5%5D=gu&showCol%5B6%5D=vl&showCol%5B7%5D=wg&showCol%5B8%5D=cr&showCol%5B9%5D=fi&showCol%5B10%5D=he&showCol%5B11%5D=sh&showCol%5B12%5D=vo&showCol%5B13%5D=dr&showCol%5B14%5D=cu&showCol%5B15%5D=fr&showCol%5B16%5D=lo&showCol%5B17%5D=bl&showCol%5B18%5D=ac&showCol%5B19%5D=sp&showCol%5B20%5D=ag&showCol%5B21%5D=re&showCol%5B22%5D=ba&showCol%5B23%5D=so&showCol%5B24%5D=ju&showCol%5B25%5D=st&showCol%5B26%5D=sr&showCol%5B27%5D=ln&showCol%5B28%5D=ar&showCol%5B29%5D=in&showCol%5B30%5D=vi&showCol%5B31%5D=pe&showCol%5B32%5D=cm&showCol%5B33%5D=ma&showCol%5B34%5D=sa&showCol%5B35%5D=sl&showCol%5B36%5D=gd&showCol%5B37%5D=gh&showCol%5B38%5D=gc&showCol%5B39%5D=gp&showCol%5B40%5D=gr&showCol%5B41%5D=wk&showCol%5B42%5D=sk&r=230002&set=true")
driver.get("https://sofifa.com/players?type=all&ct%5B0%5D=8&na%5B0%5D=97&na%5B1%5D=101&na%5B2%5D=104&na%5B3%5D=103&na%5B4%5D=110&na%5B5%5D=108&na%5B6%5D=111&na%5B7%5D=117&na%5B8%5D=118&na%5B9%5D=126&na%5B10%5D=129&na%5B11%5D=133&na%5B12%5D=136&na%5B13%5D=140&na%5B14%5D=145&lg%5B0%5D=13&lg%5B1%5D=31&lg%5B2%5D=53&lg%5B3%5D=19&lg%5B4%5D=16&showCol%5B0%5D=ae&showCol%5B1%5D=hi&showCol%5B2%5D=wi&showCol%5B3%5D=pf&showCol%5B4%5D=pt&showCol%5B5%5D=gu&showCol%5B6%5D=vl&showCol%5B7%5D=wg&showCol%5B8%5D=cr&showCol%5B9%5D=fi&showCol%5B10%5D=he&showCol%5B11%5D=sh&showCol%5B12%5D=vo&showCol%5B13%5D=dr&showCol%5B14%5D=cu&showCol%5B15%5D=fr&showCol%5B16%5D=lo&showCol%5B17%5D=bl&showCol%5B18%5D=ac&showCol%5B19%5D=sp&showCol%5B20%5D=ag&showCol%5B21%5D=re&showCol%5B22%5D=ba&showCol%5B23%5D=so&showCol%5B24%5D=ju&showCol%5B25%5D=st&showCol%5B26%5D=sr&showCol%5B27%5D=ln&showCol%5B28%5D=ar&showCol%5B29%5D=in&showCol%5B30%5D=vi&showCol%5B31%5D=pe&showCol%5B32%5D=cm&showCol%5B33%5D=ma&showCol%5B34%5D=sa&showCol%5B35%5D=sl&showCol%5B36%5D=gd&showCol%5B37%5D=gh&showCol%5B38%5D=gc&showCol%5B39%5D=gp&showCol%5B40%5D=gr&showCol%5B41%5D=wk&showCol%5B42%5D=sk&r=240003&set=true")

SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 135
Current browser version is 137.0.7151.104 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
	GetHandleVerifier [0x00007FF7AB525335+78597]
	GetHandleVerifier [0x00007FF7AB525390+78688]
	(No symbol) [0x00007FF7AB2D91AA]
	(No symbol) [0x00007FF7AB31D1CF]
	(No symbol) [0x00007FF7AB31C21B]
	(No symbol) [0x00007FF7AB3165A8]
	(No symbol) [0x00007FF7AB311A5D]
	(No symbol) [0x00007FF7AB3651E5]
	(No symbol) [0x00007FF7AB3647A0]
	(No symbol) [0x00007FF7AB356EC3]
	(No symbol) [0x00007FF7AB3203F8]
	(No symbol) [0x00007FF7AB321163]
	GetHandleVerifier [0x00007FF7AB7CEEED+2870973]
	GetHandleVerifier [0x00007FF7AB7C9698+2848360]
	GetHandleVerifier [0x00007FF7AB7E6973+2967875]
	GetHandleVerifier [0x00007FF7AB54017A+188746]
	GetHandleVerifier [0x00007FF7AB54845F+222255]
	GetHandleVerifier [0x00007FF7AB52D2B4+111236]
	GetHandleVerifier [0x00007FF7AB52D462+111666]
	GetHandleVerifier [0x00007FF7AB513589+5465]
	BaseThreadInitThunk [0x00007FF991B4E8D7+23]
	RtlUserThreadStart [0x00007FF992FBC34C+44]

### configuring the driver to scrap the table from the page for each of the three seasons and clicking the NEXT buttom if there is another page

In [ ]:

# Configura il driver con timeout più alto
driver.set_page_load_timeout(45)  # Aspetta fino a 25 secondi per il caricamento della pagina

all_data = []

try:
    while True:
        # Aspetta che la tabella sia caricata
        WebDriverWait(driver, 15).until(EC.presence_of_element_located((By.TAG_NAME, 'table')))
        
        # Trova la tabella e le righe
        table = driver.find_element(By.TAG_NAME, 'table')
        rows = table.find_elements(By.TAG_NAME, 'tr')
        
        for row in rows:
            cells = row.find_elements(By.TAG_NAME, 'td')
            cells_text = [cell.text.strip() for cell in cells]
            if cells_text:
                all_data.append(cells_text)

        # Scorri fino in fondo per assicurarti che il pulsante "Next" sia visibile
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)

        # **🔹 Seleziona il pulsante "Next" esattamente evitando "Previous"**
        try:
            pagination = driver.find_element(By.CLASS_NAME, "pagination")
            next_buttons = pagination.find_elements(By.CLASS_NAME, "button")
            
            # Trova l'elemento "Next" tra i pulsanti
            next_button = None
            for btn in next_buttons:
                if "Next" in btn.text:
                    next_button = btn
                    break
            
            if next_button is None:
                print("Nessun pulsante 'Next' trovato. Fine delle pagine.")
                break  
        
        except:
            print(" Nessun pulsante 'Next' trovato. Fine delle pagine.")
            break  

        # Scroll fino al pulsante per renderlo visibile
        driver.execute_script("arguments[0].scrollIntoView();", next_button)
        time.sleep(1)

        # Usa JavaScript per cliccare se il click classico fallisce
        driver.execute_script("arguments[0].click();", next_button)

        # Aspetta che la nuova pagina carichi i dati
        WebDriverWait(driver, 25).until(EC.staleness_of(table))

    # Converti i dati in DataFrame
    df = pd.DataFrame(all_data)

    # Salva in un file CSV
    df.to_csv('all_players_2023_24.csv', index=False, encoding='utf-8')
    print("Dati di tutte le pagine salvati in all_players_2023.csv")

finally:
    driver.quit()

In [ ]:
final_players_2022 = pd.read_csv("all_players_2023_24.csv")
final_players_2022.head()

### deleting the first column for each table

In [ ]:
# Drop the first column (column 0)
final_players_2022 = final_players_2022.drop(final_players_2022.columns[0], axis=1)

In [ ]:
final_players_2022.head()

### For each season add the current season on the 46 column

In [ ]:
final_players_2022.iloc[:, 45] = '23/24'

In [ ]:
final_players_2022.columns = ['Name', 'Age','Potential','Team & Contract','Height','Weight','Prefered foot','Growth','value','Wage',
                      'Crossing','Finishing','Heading accuracy','Short passing','Volleys','Dribbling',
                      'Curve','FK accuracy','Long passing','Ball control','Acceleration','Sprint speed','Agility','Reactions',
                      'Balance','Shot power','Jumping','Stamina','Strength','Long shots','Aggression','Interceptions','Vision',
                      'Penalties','Composure','Defensive awareness','Standing tackle','Sliding tackle','GK diving','GK Handling',
                       'GK Kicking','GK Positioning','GK Reflexes','Weak foot','Skill moves','Season'
                      ]

In [ ]:
final_players_2022.head(15)

In [ ]:
final_players_2022.to_csv('player_2023_24_final.csv', index=False)

### Merge the three dataset extracted from the page

In [377]:
player_2022final = pd.read_csv("player_2021_22_final.csv")
player_2023final = pd.read_csv("player_2022_23_final.csv")
player_2024final = pd.read_csv("player_2023_24_final.csv")

In [379]:
csv_files=["player_2021_22_final.csv","player_2022_23_final.csv","player_2023_24_final.csv"]
merged_data = pd.concat([pd.read_csv(file) for file in csv_files])

# Save the merged data into a single CSV file
merged_data.to_csv("players_all_3_seasons.csv", index=False)

### Separating Player Names and Roles in the Dataset

In [381]:
# Lista dei ruoli conosciuti
roles_list = ["CB", "LB", "RB", "ST", "LW", "RW", "CM", "CDM", "CAM", "CF", "RM", "LM", "LWB", "RWB","GK"]

# Funzione per separare nome e ruoli
def split_name_and_roles_safe(name):
    # Dividi la stringa in parole
    parts = name.split()
    # Inizializza liste per nome e ruoli
    roles = []
    name_parts = []
    # Itera sulle parole dalla fine all'inizio
    for word in reversed(parts):
        if word in roles_list:  # Se la parola è un ruolo, aggiungila ai ruoli
            roles.insert(0, word)
        else:  # Altrimenti, considera la parola parte del nome
            name_parts.insert(0, word)
    # Ricostruisci nome e ruoli
    name_only = " ".join(name_parts)
    roles_only = ", ".join(roles)
    return name_only, roles_only
    

# Leggi il file CSV (sostituisci con il tuo file)
file_path = "players_all_3_seasons.csv"  # Modifica con il percorso del tuo file
data = pd.read_csv(file_path)

# Applica la funzione alla colonna 'Name'
data[['Name', 'Position']] = data['Name'].apply(lambda x: pd.Series(split_name_and_roles_safe(x)))

# Riorganizza le colonne per posizionare "Roles" come seconda
columns_order = ['Name', 'Position'] + [col for col in data.columns if col not in ['Name', 'Position']]
data = data[columns_order]

# Salva il risultato in un nuovo file
output_file = "statistics_players.csv"
data.to_csv(output_file, index=False)

print(f"I dati separati sono stati salvati in: {output_file}")

I dati separati sono stati salvati in: statistics_players.csv

### splitting the team & contract column and converting the value and wage of the players using the convert currency and converted the height in cm and weight in kg

In [383]:
players_all_3_seasons = pd.read_csv("statistics_players.csv")

players_all_3_seasons[['Team', 'Contract']] = players_all_3_seasons['Team & Contract'].str.split('\n', expand=True)


# Function to convert values
def convert_currency(value):
    if 'M' in value:
        return float(value.replace('€', '').replace('M', '')) * 1000000
    elif 'K' in value:
        return float(value.replace('€', '').replace('K', '')) * 1000
    else:
        return float(value.replace('€', ''))
    return value

# Apply the function to the column
players_all_3_seasons['Converted Value'] = players_all_3_seasons['value'].apply(convert_currency)
players_all_3_seasons['Converted Wage'] = players_all_3_seasons['Wage'].apply(convert_currency)

players_all_3_seasons['Height (cm)'] = players_all_3_seasons['Height'].str.extract(r'(\d+)cm').astype(int)
players_all_3_seasons['Weight (kg)'] = players_all_3_seasons['Weight'].str.extract(r'(\d+)kg').astype(int)


dic_positions = {
    'GK': 'Goalkeeper', 
    'LB': 'Left-Back', 
    'LWB': 'Left-Back', 
    'LCB': 'Centre-Back', 
    'CB': 'Centre-Back',
    'RCB': 'Centre-Back', 
    'RB': 'Right-Back', 
    'RWB': 'Right-Back', 
    'LDM': 'Defensive Midfield',
    'CDM': 'Defensive Midfield', 
    'RDM': 'Defensive Midfield', 
    'LM': 'Left Midfield', 
    'LCM': 'Central Midfield',
    'CM': 'Central Midfield', 
    'RCM': 'Central Midfield', 
    'RM': 'Right Midfield', 
    'LAM': 'Attacking Midfield',
    'CAM': 'Attacking Midfield', 
    'RAM': 'Attacking Midfield', 
    'LW': 'Left Winger', 
    'LF': 'Forward',
    'CF': 'Forward', 
    'RF': 'Forward', 
    'LS': 'Forward', 
    'ST': 'Forward',
    'RW': 'Right Winger'
}

# Display the updated DataFrame
display(players_all_3_seasons)

,Name,Position,Age,Potential,Team & Contract,Height,Weight,Prefered foot,Growth,value,...,GK Reflexes,Weak foot,Skill moves,Season,Team,Contract,Converted Value,Converted Wage,Height (cm),Weight (kg)
0,S. Mané,LW,29,89,Liverpool\n2016 ~ 2023,"175cm / 5'9""",69kg / 152lbs,Right,0,€101M,...,14,4,4,21/22,Liverpool,2016 ~ 2023,101000000.0,270000.0,175,69
1,M. Salah,RW,29,89,Liverpool\n2017 ~ 2023,"175cm / 5'9""",71kg / 157lbs,Left,0,€101M,...,14,3,4,21/22,Liverpool,2017 ~ 2023,101000000.0,270000.0,175,71
2,R. Mahrez,"RW, RM",30,86,Manchester City\n2018 ~ 2023,"179cm / 5'10""",67kg / 148lbs,Left,0,€65.5M,...,6,4,5,21/22,Manchester City,2018 ~ 2023,65500000.0,220000.0,179,67
3,K. Koulibaly,CB,30,86,Napoli\n2014 ~ 2023,"187cm / 6'2""",89kg / 196lbs,Right,0,€55.5M,...,5,3,2,21/22,Napoli,2014 ~ 2023,55500000.0,105000.0,187,89
4,W. Ndidi,"CDM, CM",24,88,Leicester City\n2017 ~ 2024,"183cm / 6'0""",74kg / 163lbs,Right,3,€66.5M,...,13,4,3,21/22,Leicester City,2017 ~ 2024,66500000.0,120000.0,183,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,M. Cissé,"RM, LM",20,72,VfB Stuttgart\n2020 ~ 2024,"178cm / 5'10""",64kg / 141lbs,Right,12,€600K,...,11,3,3,23/24,VfB Stuttgart,2020 ~ 2024,600000.0,3000.0,178,64
730,F. Fall,CB,19,76,Stade de Reims\n2023 ~ 2027,"192cm / 6'4""",80kg / 176lbs,Left,17,€550K,...,9,3,2,23/24,Stade de Reims,2023 ~ 2027,550000.0,2000.0,192,80
731,M. Loune,"CM, CAM",19,78,Eintracht Frankfurt\n2022 ~ 2025,"172cm / 5'8""",70kg / 154lbs,Right,19,€575K,...,15,3,3,23/24,Eintracht Frankfurt,2022 ~ 2025,575000.0,3000.0,172,70
732,A. Bellaarouch,GK,21,71,RC Strasbourg Alsace\n2023 ~ 2025,"188cm / 6'2""",75kg / 165lbs,Right,14,€350K,...,59,3,1,23/24,RC Strasbourg Alsace,2023 ~ 2025,350000.0,2000.0,188,75
733,S. Berkani,CDM,19,64,Clermont Foot 63\n2023 ~ 2028,"178cm / 5'10""",65kg / 143lbs,Right,7,€300K,...,7,3,2,23/24,Clermont Foot 63,2023 ~ 2028,300000.0,1000.0,178,65

### Standardizing and Replacing Player Positions in the Dataset based on the dictionary

In [385]:
# Funzione per sostituire i ruoli nella colonna Position
def replace_positions(positions):
    roles = positions.split(', ')  # Dividi i ruoli separati da una virgola
    updated_roles = [dic_positions.get(role, role) for role in roles]  # Sostituisci i ruoli
    updated_roles = list(set(updated_roles))  # Rimuovi i duplicati
    updated_roles.sort()  # Ordina i ruoli in ordine alfabetico (opzionale)
    return ', '.join(updated_roles)  # Ritorna i ruoli sostituiti come una stringa separata da virgole

# Applicare la funzione alla colonna 'Position'

# Sostituire i valori nella colonna "Position" usando il dizionario
players_all_3_seasons['Position'] = players_all_3_seasons['Position'].apply(replace_positions)

### Normalizing Player Names and Teams: Lowercasing and Removing Accents

In [387]:
import re
from unidecode import unidecode

# Function to abbreviate name: first initial + last part
def abbreviate_name(name):
    if isinstance(name, str):
        name = unidecode(name.lower())
        name = re.sub(r"[^a-zA-Z.\s]", "", name)  # tieni anche i punti
        parts = name.split()
        if len(parts) >= 2:
            # se il primo elemento è già un'iniziale (tipo "r.") la lasciamo così
            first = parts[0] if parts[0].endswith('.') else parts[0][0] + '.'
            last = parts[-1]
            return f"{first}{last}"
        return name
    return name

# Apply to player names
players_all_3_seasons['Name'] = players_all_3_seasons['Name'].apply(abbreviate_name)

# Normalize team names
players_all_3_seasons['Team'] = players_all_3_seasons['Team'].apply(
    lambda x: unidecode(x.lower()) if isinstance(x, str) else x
)

In [354]:
players_all_3_seasons.head()

,Name,Position,Age,Potential,Team & Contract,Height,Weight,Prefered foot,Growth,value,...,GK Reflexes,Weak foot,Skill moves,Season,Team,Contract,Converted Value,Converted Wage,Height (cm),Weight (kg)
0,s.mane,Left Winger,29,89,Liverpool\n2016 ~ 2023,"175cm / 5'9""",69kg / 152lbs,Right,0,€101M,...,14,4,4,21/22,liverpool,2016 ~ 2023,101000000.0,270000.0,175,69
1,m.salah,Right Winger,29,89,Liverpool\n2017 ~ 2023,"175cm / 5'9""",71kg / 157lbs,Left,0,€101M,...,14,3,4,21/22,liverpool,2017 ~ 2023,101000000.0,270000.0,175,71
2,r.mahrez,"Right Midfield, Right Winger",30,86,Manchester City\n2018 ~ 2023,"179cm / 5'10""",67kg / 148lbs,Left,0,€65.5M,...,6,4,5,21/22,manchester city,2018 ~ 2023,65500000.0,220000.0,179,67
3,k.koulibaly,Centre-Back,30,86,Napoli\n2014 ~ 2023,"187cm / 6'2""",89kg / 196lbs,Right,0,€55.5M,...,5,3,2,21/22,napoli,2014 ~ 2023,55500000.0,105000.0,187,89
4,w.ndidi,"Central Midfield, Defensive Midfield",24,88,Leicester City\n2017 ~ 2024,"183cm / 6'0""",74kg / 163lbs,Right,3,€66.5M,...,13,4,3,21/22,leicester city,2017 ~ 2024,66500000.0,120000.0,183,74

### Standardizing Team Names Using a Mapping Dictionary

In [389]:
team_mapping = {
    'liverpool': 'liverpool fc',
    'chelsea': 'chelsea fc',
    'manchester city': 'manchester city',
    'napoli': 'ssc napoli',
    'paris saint-germain': 'paris saint-germain',
    'arsenal': 'arsenal fc',
    'leicester city': 'leicester city',
    'ac milan': 'ac milan',
    'crystal palace': 'crystal palace',
    'sevilla fc': 'sevilla fc',
    'brighton & hove albion': 'brighton & hove albion',
    'rc lens': 'rc lens',
    'ogc nice': 'ogc nice',
    'bayer 04 leverkusen': 'bayer 04 leverkusen',
    'stade rennais fc': 'stade rennais fc',
    '1. fc koln': '1.fc koln',
    'villarreal cf': 'villarreal cf',
    'west ham united': 'west ham united',
    'wolverhampton wanderers': 'wolverhampton wanderers',
    'burnley': 'burnley fc',
    'olympique lyonnais': 'olympique lyon',
    'borussia monchengladbach': 'borussia monchengladbach',
    'rb leipzig': 'rb leipzig',
    'aston villa': 'aston villa',
    'manchester united': 'manchester united',
    'southampton': 'southampton fc',
    'watford': 'watford fc',
    'fc nantes': 'fc nantes',
    'rc strasbourg alsace': 'rc strasbourg alsace',
    'olympique de marseille': 'olympique marseille',
    'angers sco': 'angers sco',
    'as saint-etienne': 'as saint-etienne',
    'atalanta': 'atalanta bc',
    'lazio': 'ss lazio',
    'venezia': 'venezia fc',
    'everton': 'everton fc',
    'stade brestois 29': 'stade brestois 29',
    'stade de reims': 'stade reims',
    '1. fc union berlin': '1.fc union berlin',
    'tsg 1899 hoffenheim': 'tsg 1899 hoffenheim',
    'cagliari': 'cagliari calcio',
    'fiorentina': 'acf fiorentina',
    'sassuolo': 'us sassuolo',
    'real betis balompie': 'real betis balompie',
    'rc celta': 'celta de vigo',
    'cadiz cf': 'cadiz cf',
    'brentford': 'brentford fc',
    'as monaco': 'as monaco',
    'clermont foot 63': 'clermont foot 63',
    'fc bayern munchen': 'bayern munich',
    'vfb stuttgart': 'vfb stuttgart',
    'hertha bsc': 'hertha bsc',
    'granada cf': 'granada cf',
    'fc girondins de bordeaux': 'fc girondins bordeaux',
    'fc metz': 'fc metz',
    'roma': 'as roma',
    'torino': 'torino fc',
    'rcd mallorca': 'rcd mallorca',
    'eintracht frankfurt': 'eintracht frankfurt',
    'valencia cf': 'valencia cf',
    'rayo vallecano': 'rayo vallecano',
    'montpellier hsc': 'montpellier hsc',
    'fc lorient': 'fc lorient',
    'estac troyes': 'estac troyes',
    'spvgg greuther furth': 'spvgg greuther furth',
    'udinese': 'udinese calcio',
    'hellas verona fc': 'hellas verona',
    'us salernitana 1919': 'us salernitana 1919',
    'genoa': 'genoa cfc',
    'bologna': 'bologna fc 1909',
    'deportivo alaves': 'deportivo alaves',
    'vfl bochum 1848': 'vfl bochum',
    'fc augsburg': 'fc augsburg',
    'spezia': 'spezia calcio',
    'fc barcelona': 'fc barcelona',
    'lille osc': 'losc lille',
    'getafe cf': 'getafe cf',
    'borussia dortmund': 'borussia dortmund',
    'inter': 'inter milan',
    'athletic club': 'athletic bilbao',
    'tottenham hotspur': 'tottenham hotspur',
    'nottingham forest': 'nottingham forest',
    'afc bournemouth': 'afc bournemouth',
    'real sociedad': 'real sociedad',
    'ac ajaccio': 'ac ajaccio',
    'sc freiburg': 'sc freiburg',
    'vfl wolfsburg': 'vfl wolfsburg',
    'empoli': 'fc empoli',
    'sampdoria' : 'uc sampdoria',
    'rcd espanyol' : 'rcd espanyol barcelona',
    'cremonese' : 'us cremonese',
    'toulouse fc': 'fc toulouse',
    '1. fsv mainz 05' : '1.fsv mainz 05',
    'frosinone' : 'frosinone calcio',
    'lecce' : 'us lecce',
    'monza' : 'ac monza'

}
def replace_team_name(team_name):
    return team_mapping.get(team_name, team_name)

# Applichiamo la funzione alla colonna 'team'
players_all_3_seasons['Team'] = players_all_3_seasons['Team'].apply(replace_team_name)

In [358]:
players_all_3_seasons.head()

,Name,Position,Age,Potential,Team & Contract,Height,Weight,Prefered foot,Growth,value,...,GK Reflexes,Weak foot,Skill moves,Season,Team,Contract,Converted Value,Converted Wage,Height (cm),Weight (kg)
0,s.mane,Left Winger,29,89,Liverpool\n2016 ~ 2023,"175cm / 5'9""",69kg / 152lbs,Right,0,€101M,...,14,4,4,21/22,liverpool fc,2016 ~ 2023,101000000.0,270000.0,175,69
1,m.salah,Right Winger,29,89,Liverpool\n2017 ~ 2023,"175cm / 5'9""",71kg / 157lbs,Left,0,€101M,...,14,3,4,21/22,liverpool fc,2017 ~ 2023,101000000.0,270000.0,175,71
2,r.mahrez,"Right Midfield, Right Winger",30,86,Manchester City\n2018 ~ 2023,"179cm / 5'10""",67kg / 148lbs,Left,0,€65.5M,...,6,4,5,21/22,manchester city,2018 ~ 2023,65500000.0,220000.0,179,67
3,k.koulibaly,Centre-Back,30,86,Napoli\n2014 ~ 2023,"187cm / 6'2""",89kg / 196lbs,Right,0,€55.5M,...,5,3,2,21/22,ssc napoli,2014 ~ 2023,55500000.0,105000.0,187,89
4,w.ndidi,"Central Midfield, Defensive Midfield",24,88,Leicester City\n2017 ~ 2024,"183cm / 6'0""",74kg / 163lbs,Right,3,€66.5M,...,13,4,3,21/22,leicester city,2017 ~ 2024,66500000.0,120000.0,183,74

In [244]:
unique_teams = players_all_3_seasons['Team'].unique()
print(unique_teams)

['liverpool fc' 'chelsea fc' 'manchester city' 'ssc napoli'
 'paris saint-germain' 'arsenal fc' 'leicester city' 'ac milan'
 'crystal palace' 'sevilla fc' 'brighton & hove albion' 'rc lens'
 'ogc nice' 'bayer 04 leverkusen' 'stade rennais fc' '1.fc koln'
 'villarreal cf' 'west ham united' 'wolverhampton wanderers' 'burnley fc'
 'olympique lyon' 'borussia monchengladbach' 'rb leipzig' 'aston villa'
 'manchester united' 'southampton fc' 'watford fc' 'fc nantes'
 'rc strasbourg alsace' 'olympique marseille' 'angers sco'
 'as saint-etienne' 'atalanta bc' 'ss lazio' 'venezia fc' 'everton fc'
 'stade brestois 29' 'stade reims' '1.fc union berlin'
 'tsg 1899 hoffenheim' 'cagliari calcio' 'acf fiorentina' 'us sassuolo'
 'real betis balompie' 'celta de vigo' 'cadiz cf' 'brentford fc'
 'as monaco' 'clermont foot 63' 'bayern munich' 'vfb stuttgart'
 'hertha bsc' 'granada cf' 'fc girondins bordeaux' 'fc metz' 'as roma'
 'torino fc' 'rcd mallorca' 'eintracht frankfurt' 'valencia cf'
 'rayo vallecano' 'montpellier hsc' 'fc lorient' 'estac troyes'
 'spvgg greuther furth' 'udinese calcio' 'hellas verona'
 'us salernitana 1919' 'genoa cfc' 'bologna fc 1909' 'deportivo alaves'
 'vfl bochum' 'fc augsburg' 'spezia calcio' 'fc barcelona' 'losc lille'
 'getafe cf' 'borussia dortmund' 'inter milan' 'athletic bilbao'
 'tottenham hotspur' 'nottingham forest' 'afc bournemouth' 'real sociedad'
 'ac ajaccio' 'sc freiburg' 'vfl wolfsburg' 'fc empoli' 'us cremonese'
 'real valladolid cf' 'aj auxerre' 'fc toulouse' 'us lecce' 'fulham fc'
 'uc sampdoria' '1.fsv mainz 05' 'ca osasuna' 'ud almeria' 'elche cf'
 'girona fc' 'fc schalke 04' 'rcd espanyo barcelona' 'real madrid'
 'ud las palmas' 'sv werder bremen' 'frosinone calcio' 'luton town'
 'le havre ac' 'ac monza' 'sv darmstadt 98' 'sheffield united']

### creating the ID by removing the point in the name of the players and create the ID concatanating the name,the team and the season using the underscore

In [391]:
# Funzione per creare l'ID
def create_player_id(row):
    # Rimuoviamo il punto nel nome
    name_parts = row['Name'].replace('.', ' ').split()

    # Verifica che il nome abbia almeno due parti (nome e cognome)
    if len(name_parts) >= 2:
        first_name_initial = name_parts[0][0].lower()  # Prima lettera del nome
        last_name = name_parts[1].lower()  # Cognome
    else:
        # Se non c'è un cognome, usiamo l'intero nome (senza punto) per la parte finale
        first_name_initial = name_parts[0][0].lower()
        last_name = name_parts[0][1:].lower()  # Aggiunge il resto del nome

    # Creiamo l'ID come lettera_cognome_squadra_stagione
    player_id = f"{first_name_initial}_{last_name}_{row['Team'].replace('.', ' ').replace(' ', '_').lower()}_{row['Season'].replace('/', ' ').replace(' ', '_').lower()}"
    
    return player_id

# Applichiamo la funzione per creare la colonna 'ID'
players_all_3_seasons['ID'] = players_all_3_seasons.apply(create_player_id, axis=1)

# Mostriamo il risultato
print(players_all_3_seasons)

              Name                              Position  Age Potential  \
0           s.mane                           Left Winger   29        89
1          m.salah                          Right Winger   29        89
2         r.mahrez          Right Midfield, Right Winger   30        86
3      k.koulibaly                           Centre-Back   30        86
4          w.ndidi  Central Midfield, Defensive Midfield   24        88
..             ...                                   ...  ...       ...
729        m.cisse         Left Midfield, Right Midfield   20        72
730         f.fall                           Centre-Back   19        76
731        m.loune  Attacking Midfield, Central Midfield   19        78
732  a.bellaarouch                            Goalkeeper   21        71
733      s.berkani                    Defensive Midfield   19        64

                       Team & Contract         Height         Weight  \
0               Liverpool\n2016 ~ 2023   175cm / 5'9"  69kg / 152lbs
1               Liverpool\n2017 ~ 2023   175cm / 5'9"  71kg / 157lbs
2         Manchester City\n2018 ~ 2023  179cm / 5'10"  67kg / 148lbs
3                  Napoli\n2014 ~ 2023   187cm / 6'2"  89kg / 196lbs
4          Leicester City\n2017 ~ 2024   183cm / 6'0"  74kg / 163lbs
..                                 ...            ...            ...
729         VfB Stuttgart\n2020 ~ 2024  178cm / 5'10"  64kg / 141lbs
730        Stade de Reims\n2023 ~ 2027   192cm / 6'4"  80kg / 176lbs
731   Eintracht Frankfurt\n2022 ~ 2025   172cm / 5'8"  70kg / 154lbs
732  RC Strasbourg Alsace\n2023 ~ 2025   188cm / 6'2"  75kg / 165lbs
733      Clermont Foot 63\n2023 ~ 2028  178cm / 5'10"  65kg / 143lbs

    Prefered foot  Growth   value  ... Weak foot Skill moves Season  \
0           Right       0   €101M  ...         4           4  21/22
1            Left       0   €101M  ...         3           4  21/22
2            Left       0  €65.5M  ...         4           5  21/22
3           Right       0  €55.5M  ...         3           2  21/22
4           Right       3  €66.5M  ...         4           3  21/22
..            ...     ...     ...  ...       ...         ...    ...
729         Right      12   €600K  ...         3           3  23/24
730          Left      17   €550K  ...         3           2  23/24
731         Right      19   €575K  ...         3           3  23/24
732         Right      14   €350K  ...         3           1  23/24
733         Right       7   €300K  ...         3           2  23/24

                     Team     Contract Converted Value Converted Wage  \
0            liverpool fc  2016 ~ 2023     101000000.0       270000.0
1            liverpool fc  2017 ~ 2023     101000000.0       270000.0
2         manchester city  2018 ~ 2023      65500000.0       220000.0
3              ssc napoli  2014 ~ 2023      55500000.0       105000.0
4          leicester city  2017 ~ 2024      66500000.0       120000.0
..                    ...          ...             ...            ...
729         vfb stuttgart  2020 ~ 2024        600000.0         3000.0
730           stade reims  2023 ~ 2027        550000.0         2000.0
731   eintracht frankfurt  2022 ~ 2025        575000.0         3000.0
732  rc strasbourg alsace  2023 ~ 2025        350000.0         2000.0
733      clermont foot 63  2023 ~ 2028        300000.0         1000.0

    Height (cm) Weight (kg)                                        ID
0           175          69                 s_mane_liverpool_fc_21_22
1           175          71                m_salah_liverpool_fc_21_22
2           179          67            r_mahrez_manchester_city_21_22
3           187          89              k_koulibaly_ssc_napoli_21_22
4           183          74              w_ndidi_leicester_city_21_22
..          ...         ...                                       ...
729         178          64               m_cisse_vfb_stuttgart_23_24
730         192          80                  f_fall_stade_reims_23_24
731         172          70         m_loune_eintracht_frankfurt_23_24
732         188          75  a_bellaarouch_rc_strasbourg_alsace_23_24
733         178          65          s_berkani_clermont_foot_63_23_24

[734 rows x 54 columns]

In [214]:
display(players_all_3_seasons.columns)

Index(['Name', 'Position', 'Age', 'Potential', 'Team & Contract', 'Height',
       'Weight', 'Prefered foot', 'Growth', 'value', 'Wage', 'Crossing',
       'Finishing', 'Heading accuracy', 'Short passing', 'Volleys',
       'Dribbling', 'Curve', 'FK accuracy', 'Long passing', 'Ball control',
       'Acceleration', 'Sprint speed', 'Agility', 'Reactions', 'Balance',
       'Shot power', 'Jumping', 'Stamina', 'Strength', 'Long shots',
       'Aggression', 'Interceptions', 'Vision', 'Penalties', 'Composure',
       'Defensive awareness', 'Standing tackle', 'Sliding tackle', 'GK diving',
       'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes',
       'Weak foot', 'Skill moves', 'Season', 'Team', 'Contract',
       'Converted Value', 'Converted Wage', 'Height (cm)', 'Weight (kg)',
       'ID'],
      dtype='object')

In [393]:
players_all_3_seasons.to_csv('players_all_3_seasons.csv', index=False)

In [399]:
def process_positions(file_path, output_path):
    # Carica il file CSV
    df = pd.read_csv(file_path)
    
    # Verifica i nomi delle colonne
    print("Colonne del dataset:", df.columns)
    
    # Assicurati che la colonna "Position" esista
    if "Position" not in df.columns:
        raise ValueError("La colonna 'Position' non esiste nel dataset.")
    
    # Funzione per elaborare le posizioni
    def split_positions(position):
        # Assicurati che la posizione sia trattata come stringa
        position = str(position).strip()
        
        # Se la posizione è vuota, ritorna valori vuoti
        if not position:
            return pd.Series(["", "", 0])
        
        # Split delle posizioni, rimuovendo gli spazi extra
        positions = [pos.strip() for pos in position.split(",")]
        
        # La prima posizione è la posizione principale
        main_position = positions[0] if positions else ""
        
        # Le posizioni alternative sono tutte le posizioni eccetto la principale
        alternative_positions = ", ".join(positions[1:]) if len(positions) > 1 else ""
        
        # Conta le posizioni alternative
        alternative_count = len(positions) - 1 if len(positions) > 1 else 0
        
        return pd.Series([main_position, alternative_positions, alternative_count])
    
    # Applica la funzione a tutte le righe
    df[["Main Position", "Alternative Positions", "Alternative Count"]] = df["Position"].apply(split_positions)
    
    # Drop delle colonne "Position" e "Weight" se esistono
    df.drop(columns=[col for col in ["Position", "Weight","Team & Contract","Height"] if col in df.columns], inplace=True)
    
    # Salva il nuovo dataset
    df.to_csv(output_path, index=False)
    print(f"File salvato con successo: {output_path}")

# Esempio di utilizzo
input_file = "players_all_3_seasons.csv"  # Sostituisci con il percorso corretto
output_file = "filtered_with_seperation.csv"
process_positions(input_file, output_file)

Colonne del dataset: Index(['Name', 'Position', 'Age', 'Potential', 'Team & Contract', 'Height',
       'Weight', 'Prefered foot', 'Growth', 'value', 'Wage', 'Crossing',
       'Finishing', 'Heading accuracy', 'Short passing', 'Volleys',
       'Dribbling', 'Curve', 'FK accuracy', 'Long passing', 'Ball control',
       'Acceleration', 'Sprint speed', 'Agility', 'Reactions', 'Balance',
       'Shot power', 'Jumping', 'Stamina', 'Strength', 'Long shots',
       'Aggression', 'Interceptions', 'Vision', 'Penalties', 'Composure',
       'Defensive awareness', 'Standing tackle', 'Sliding tackle', 'GK diving',
       'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes',
       'Weak foot', 'Skill moves', 'Season', 'Team', 'Contract',
       'Converted Value', 'Converted Wage', 'Height (cm)', 'Weight (kg)',
       'ID'],
      dtype='object')
File salvato con successo: filtered_with_seperation.csv

In [403]:
filtered_with_seperation = pd.read_csv("filtered_with_seperation.csv")

In [425]:
# List of columns to convert
columns_to_convert = [
    'Crossing', 'Finishing', 'Heading accuracy', 'Short passing', 'Volleys',
    'Dribbling', 'Curve', 'FK accuracy', 'Long passing', 'Ball control',
    'Acceleration', 'Sprint speed', 'Agility', 'Reactions', 'Balance',
    'Shot power', 'Jumping', 'Stamina', 'Strength', 'Long shots',
    'Aggression', 'Interceptions', 'Vision', 'Penalties', 'Composure',
    'Defensive awareness', 'Standing tackle', 'Sliding tackle',
    'GK diving', 'GK Handling', 'GK Kicking', 'Potential','GK Reflexes'
]

# Loop through and convert each column
for col in columns_to_convert:
    filtered_with_seperation[col] = pd.to_numeric(filtered_with_seperation[col], errors='coerce')
    filtered_with_seperation[col] = filtered_with_seperation[col].fillna(0).astype(np.int64)

# Check results
print(filtered_with_seperation[columns_to_convert].dtypes)

Crossing               int64
Finishing              int64
Heading accuracy       int64
Short passing          int64
Volleys                int64
Dribbling              int64
Curve                  int64
FK accuracy            int64
Long passing           int64
Ball control           int64
Acceleration           int64
Sprint speed           int64
Agility                int64
Reactions              int64
Balance                int64
Shot power             int64
Jumping                int64
Stamina                int64
Strength               int64
Long shots             int64
Aggression             int64
Interceptions          int64
Vision                 int64
Penalties              int64
Composure              int64
Defensive awareness    int64
Standing tackle        int64
Sliding tackle         int64
GK diving              int64
GK Handling            int64
GK Kicking             int64
Potential              int64
GK Reflexes            int64
dtype: object

In [427]:
filtered_with_seperation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734 entries, 0 to 733
Data columns (total 53 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   734 non-null    object
 1   Age                    734 non-null    int64
 2   Potential              734 non-null    int64
 3   Prefered foot          734 non-null    object
 4   Growth                 734 non-null    int64
 5   value                  734 non-null    object
 6   Wage                   734 non-null    object
 7   Crossing               734 non-null    int64
 8   Finishing              734 non-null    int64
 9   Heading accuracy       734 non-null    int64
 10  Short passing          734 non-null    int64
 11  Volleys                734 non-null    int64
 12  Dribbling              734 non-null    int64
 13  Curve                  734 non-null    int64
 14  FK accuracy            734 non-null    int64
 15  Long passing           734 non-null    int64
 16  Ball control           734 non-null    int64
 17  Acceleration           734 non-null    int64
 18  Sprint speed           734 non-null    int64
 19  Agility                734 non-null    int64
 20  Reactions              734 non-null    int64
 21  Balance                734 non-null    int64
 22  Shot power             734 non-null    int64
 23  Jumping                734 non-null    int64
 24  Stamina                734 non-null    int64
 25  Strength               734 non-null    int64
 26  Long shots             734 non-null    int64
 27  Aggression             734 non-null    int64
 28  Interceptions          734 non-null    int64
 29  Vision                 734 non-null    int64
 30  Penalties              734 non-null    int64
 31  Composure              734 non-null    int64
 32  Defensive awareness    734 non-null    int64
 33  Standing tackle        734 non-null    int64
 34  Sliding tackle         734 non-null    int64
 35  GK diving              734 non-null    int64
 36  GK Handling            734 non-null    int64
 37  GK Kicking             734 non-null    int64
 38  GK Positioning         734 non-null    int64
 39  GK Reflexes            734 non-null    int64
 40  Weak foot              734 non-null    int64
 41  Skill moves            734 non-null    int64
 42  Season                 734 non-null    object
 43  Team                   734 non-null    object
 44  Contract               734 non-null    object
 45  Converted Value        734 non-null    float64
 46  Converted Wage         734 non-null    float64
 47  Height (cm)            734 non-null    int64
 48  Weight (kg)            734 non-null    int64
 49  ID                     734 non-null    object
 50  Main Position          734 non-null    object
 51  Alternative Positions  426 non-null    object
 52  Alternative Count      734 non-null    int64
dtypes: float64(2), int64(41), object(10)
memory usage: 304.1+ KB

In [429]:
filtered_with_seperation.to_csv('filtered_with_seperation.csv', index=False)

### saving the dataset in a new one with the new changes

In [ ]:
df = pd.read_csv("players_gianluca.csv")

In [ ]:
df_result.info()

In [ ]:
df_result.head()

In [ ]:
df_result.to_csv('players_gianluca2.csv', index=False)

In [ ]:
players_all_3_seasons.head()

In [ ]:
print(players_all_3_seasons.columns.tolist())

### salvataggio file in un database relazionale

In [234]:
# Carica i file CSV
df1 = pd.read_csv('filtered_with_seperation.csv')
df2 = pd.read_csv('players_gian.csv')

In [236]:
from sqlalchemy import create_engine

# Creare una connessione al database SQLite (modifica con il tuo database)
engine = create_engine('sqlite:///my_database.db')

In [238]:
# Salva il primo DataFrame come una tabella nel database
df1.to_sql('table1', con=engine, if_exists='replace', index=False)

# Salva il secondo DataFrame come una tabella nel database
df2.to_sql('table2', con=engine, if_exists='replace', index=False)

1044

In [240]:
# Verifica che i dati siano stati caricati
query = "SELECT * FROM table1 LIMIT 5"
df_query = pd.read_sql(query, con=engine)
print(df_query)

           Name  Age  Potential               Team & Contract         Height  \
0      m. salah   29         91        Liverpool\n2017 ~ 2023   175cm / 5'9"
1       s. mane   29         89        Liverpool\n2016 ~ 2023   175cm / 5'9"
2      e. mendy   29         87          Chelsea\n2020 ~ 2025   197cm / 6'6"
3     r. mahrez   30         86  Manchester City\n2018 ~ 2025  179cm / 5'10"
4  k. koulibaly   30         86           Napoli\n2014 ~ 2023   187cm / 6'2"

  Prefered foot  Growth   value   Wage  Crossing  ...             Team  \
0          Left       0   €129M  €350K        81  ...     liverpool fc
1         Right       0   €101M  €270K        78  ...     liverpool fc
2         Right       1    €52M  €140K        10  ...       chelsea fc
3          Left       0  €65.5M  €220K        81  ...  manchester city
4         Right       0  €55.5M  €105K        30  ...       ssc napoli

      Contract  Converted Value  Converted Wage  Height (cm)  Weight (kg)  \
0  2017 ~ 2023      129000000.0        350000.0          175           71
1  2016 ~ 2023      101000000.0        270000.0          175           69
2  2020 ~ 2025       52000000.0        140000.0          197           86
3  2018 ~ 2025       65500000.0        220000.0          179           67
4  2014 ~ 2023       55500000.0        105000.0          187           89

                               ID   Main Position  Alternative Positions  \
0      m_salah_liverpool_fc_21_22    Right Winger                   None
1       s_mane_liverpool_fc_21_22         Forward            Left Winger
2        e_mendy_chelsea_fc_21_22      Goalkeeper                   None
3  r_mahrez_manchester_city_21_22  Right Midfield           Right Winger
4    k_koulibaly_ssc_napoli_21_22     Centre-Back                   None

   Alternative Count
0                  0
1                  1
2                  0
3                  1
4                  0

[5 rows x 55 columns]

In [ ]:
# Verifica che i dati siano stati caricati
query = "SELECT * FROM table2 LIMIT 5"
df_query = pd.read_sql(query, con=engine)
print(df_query)

In [ ]:
defy2 = df_result.groupby('ID').size().sort_values(ascending=False).reset_index(name='count')
defy2[defy2['count']>1]

In [ ]:
# verifica doppiaggi

defy= df2.groupby('ID').size().sort_values(ascending=False).reset_index(name='count')
defy[defy['count']>1]

In [ ]:
iop['Debut Date'] = pd.to_datetime(iop['Debut Date'], dayfirst=True, errors='coerce')

# Ordina il dataset per 'Short Name' e poi per 'Debut Date' in ordine decrescente
df_sorted = iop.sort_values(by=['Player', 'Debut Date'], ascending=[True, False])

# Raggruppa per 'Short Name', mantieni la riga con la data di debutto più recente e somma i goal
df_result = df_sorted.groupby('Player', as_index=False).agg({
    'Debut Date': 'first',  # Mantieni la data più recente
    'Goals': 'sum',         # Somma i goal
    'League': 'first',      # Mantieni altre colonne se necessario (puoi aggiungerle qui)
    'Season': 'first',
    'Country': 'first',
    'Player': 'first',
    'Position': 'first',
    'Club': 'first',
    'Appearances': 'sum'    # Facoltativo: somma anche le apparizioni, se ha senso
})

In [ ]:
df_result

In [ ]:
defy2= df1.groupby('ID').size().sort_values(ascending=False).reset_index(name='count')
defy2[defy2['count']>1]

## MERGING THE TWO DATASETS

In [ ]:
df_merged = pd.merge(df1, df2, on='ID')
df_merged.to_csv('merged_dataset.csv', index=False)